version: '3'
services:
  ml_model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Code/app.py:/app/code/app.py
      - ./Code/requirements.txt:/app/Code/requirements.txt
    working_dir: /app
    command: python code/app.py